version: "3.9"

services:
  db:
    image: postgres:15
    container_name: crm-backend
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: crm-pg
      POSTGRES_PASSWORD: crm-pg
      POSTGRES_DB: crm-pg
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
